[environments.production]
PYTHON_VERSION = "3.10"
NODE_VERSION = "18"

[services.backend]
builder = "DOCKERFILE"
dockerfilePath = "./backend/Dockerfile.production"
buildCommand = "cd backend && docker build -f Dockerfile.production -t backend ."
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100

[services.frontend]
builder = "NIXPACKS"
buildCommand = "cd frontend && npm install && npm run build"
startCommand = "cd frontend && npx serve -s build -l $PORT"
watchPatterns = ["frontend/**"]

[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "nodejs-18_x", "postgresql"]
aptPkgs = ["gcc", "g++", "make"]

[phases.install]
cmds = [
    "cd backend && pip install -r requirements.txt",
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    "cd frontend && npm run build",
    "cd backend && python -m app.utils.db_check"
]

[start]
cmd = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
