[environments.production]
PYTHON_VERSION = "3.10"
NODE_VERSION = "18"

[services.backend]
builder = "DOCKERFILE"
dockerfilePath = "./backend/Dockerfile.production"
buildCommand = "cd backend && docker build -f Dockerfile.production -t backend ."
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100

[services.frontend]
builder = "NIXPACKS"
buildCommand = "cd frontend && npm install && npm run build"
startCommand = "cd frontend && npx serve -s build -l $PORT"
watchPatterns = ["frontend/**"]
